DRAFT: [BD-26] Create combined API endpoint for exam and attempts
raccoongang/edx-proctoring pull request #21
Opened 2021-04-22 11:57 UTC by UvgenGen

[EDUCATOR-5733](https://openedx.atlassian.net/browse/EDUCATOR-5733) [BD-26] Create combined API endpoint for exam and attempts

2021-04-26 14:41 UTC, Zacharis278 commented on edx_proctoring/views.py
> +class ProctoredExamAttemptsView(ProctoredAPIView):
this class is very similar to StudentProctoredExamAttemptCollection. I think we should find a way to either make use of the existing view, or have both of these extend from a common base class.

2021-04-28 14:17 UTC, TamoshaytisV requested changes

2021-04-28 14:17 UTC, TamoshaytisV commented on edx_proctoring/api.py
> +def get_exam_attempt_data(exam_id, attempt_id, is_learning_mfe=False, request=None):
```suggestion
def get_exam_attempt_data(exam_id, attempt_id, override_exam_url=None):
```

2021-04-28 14:17 UTC, TamoshaytisV commented on edx_proctoring/api.py
> +        usage_key = UsageKey.from_string(exam['content_id'])
Move building url to a separate function or inside View

2021-04-28 15:41 UTC, TamoshaytisV commented on edx_proctoring/api.py
> +        exam_url_path = get_learning_mfe_courseware_url(course_key, section, final_target_id)
@UvgenGen i saw that in platform this function is called `make_learning_mfe_courseware_url`

2021-04-29 10:36 UTC, TamoshaytisV commented on edx_proctoring/views.py
> +class ProctoredExamAttemptsView(ProctoredAPIView):
addressed

2021-04-29 12:39 UTC, TamoshaytisV approved these changes

2021-04-29 12:39 UTC, merged