WIP [EDUCATOR-5758] Create API endpoint to provide Proctoring settings
raccoongang/edx-proctoring pull request #24
Opened 2021-05-13 15:19 UTC by UvgenGen

[EDUCATOR-5758](https://openedx.atlassian.net/browse/EDUCATOR-5758) Create API endpoint to provide Proctoring settings

2021-05-14 06:33 UTC, idegtiarov requested changes

2021-05-14 06:33 UTC, idegtiarov commented on edx_proctoring/api.py
> -    verify_and_add_wait_deadline,
Please leave a trailing comma, it is a good practice to have it.

2021-05-14 06:33 UTC, idegtiarov commented on edx_proctoring/api.py
> +def get_proctorind_settings_by_exam_id(exam_id):
```suggestion
def get_proctoring_settings_by_exam_id(exam_id):
```

2021-05-14 06:33 UTC, idegtiarov commented on edx_proctoring/api.py
> +    Returns proctorind settings and exam proctoring backend for proctored exam
Please add a period at the end of the multiple docstring's title.

2021-05-14 06:33 UTC, idegtiarov commented on edx_proctoring/api.py
> +    if not exam.get('is_proctored'):
That statement should be checked before `get_backend_provider` function.

2021-05-14 06:33 UTC, idegtiarov commented on edx_proctoring/backends/tests/test_backend.py
> +        Returns the faked metadata and configuration options for the proctoring service
Ditto

2021-05-14 06:33 UTC, idegtiarov commented on edx_proctoring/tests/test_mfe_views.py
> +        Initialize
Ditto

2021-05-14 06:33 UTC, idegtiarov commented on edx_proctoring/views.py
> +        is_learning_mfe = request.GET.get('is_learning_mfe') in ['1', 'true', 'True', True]
`True` object cannot be received from the request.GET dict like object it is always a string:
```suggestion
        is_learning_mfe = request.GET.get('is_learning_mfe') in ['1', 'true', 'True']
```

2021-05-14 06:33 UTC, idegtiarov commented on edx_proctoring/views.py
> +    Endpoint for getting settings for proctored exam.
Please split the docstring title with the body by the empty line.

2021-05-14 06:33 UTC, idegtiarov commented on edx_proctoring/views.py
> +    def get(self, request, exam_id):
Since that is a public API we have to validate the exam_id parameter otherwise it will have unexpected behavior. The second step - we need to handle errors in  the `get_proctorind_settings_by_exam_id` method it is not expected that it could raise an exception so we will have 500 instead of some meaningful message in the response

2021-05-14 17:13 UTC, UvgenGen commented on edx_proctoring/views.py
> +    def get(self, request, exam_id):
This is already handled by the get_exam_by_id function in get_proctorind_settings_by_exam_id

2021-05-14 17:39 UTC, Zacharis278 commented on edx_proctoring/api.py
> +        'proctoring_settings': getattr(settings, 'PROCTORING_SETTINGS', {}),
I'm thinking we should explicitly pull out the settings fields we want to return here. It makes the response a bit more clear for someone reading this code. Also, I'd worry if someone put something secret in that settings variable they would never know it was exposed.

2021-05-14 17:57 UTC, UvgenGen commented on edx_proctoring/views.py
> +    Endpoint for getting settings for proctored exam.
Done

2021-05-14 18:00 UTC, idegtiarov requested changes

2021-05-14 18:20 UTC, UvgenGen commented on edx_proctoring/api.py
> +    allowed_time_limit_mins = attempt.get('allowed_time_limit_mins') or 0
The attempt could contain 'allowed_time_limit_mins' with None and this raises an error. I was getting this error

2021-05-14 18:28 UTC, UvgenGen commented on edx_proctoring/api.py
> +    allowed_time_limit_mins = attempt.get('allowed_time_limit_mins') or 0
specifically the TypeError for `float(allowed_time_limit_mins)` on line 595

2021-05-18 12:35 UTC, idegtiarov requested changes

2021-05-18 12:35 UTC, idegtiarov commented on edx_proctoring/api.py
> +        'exam_proctoring_backend': {}
Please add trailing comma

2021-05-18 12:35 UTC, idegtiarov commented on edx_proctoring/api.py
> +        'platform_name': settings.PLATFORM_NAME,
I have a concern about using `settings` as a data source since we could have `sites` on the instance so settings won't reflect correctly to the expected data. 
What do you think? Does it make sense?

2021-05-19 11:25 UTC, idegtiarov commented on edx_proctoring/views.py
> +    def get(self, request, exam_id):
Thanks for the clarification

2021-05-19 11:27 UTC, idegtiarov commented on edx_proctoring/api.py
> +        'platform_name': settings.PLATFORM_NAME,
Okk will let it then as it is and discuss it internally.

2021-05-19 11:28 UTC, idegtiarov commented
@Zacharis278 Please take a look at the PR, we are ready to open it in edX repo.

2021-05-19 15:25 UTC, Zacharis278 commented on edx_proctoring/api.py
> +            provider = get_backend_provider(exam)
can you explain a bit what's going on with the exception here, afaik this just returns None if there is no backend.

2021-05-19 16:50 UTC, idegtiarov commented on edx_proctoring/api.py
> +            provider = get_backend_provider(exam)
We've faced an issue that if the exam was configured to use a proctored provider, and then for some reason proctoring provider disappears from the `settings.PROCTORING_BACKENDS` in our case after the redeployment of the devstack, `get_backend_provider` returns a `NotImplementedError`

2021-05-20 13:24 UTC, idegtiarov approved these changes

2021-05-20 14:16 UTC, Zacharis278 approved these changes

2021-05-20 14:59 UTC, merged