[BD-26] Create API endpoint to get exam review policy, add additional data to exam attempt endpoint response
raccoongang/edx-proctoring pull request #27
Opened 2021-05-24 16:06 UTC by ViktorRusakov

[OeX_Proctoring-208](https://youtrack.raccoongang.com/issue/OeX_Proctoring-208) Create API endpoint to fetch exam review policy which is needed for proctoring instructions page

2021-05-25 15:42 UTC, Zacharis278 approved these changes
LGTM. Just one question on what we're using the new attempt fields for

2021-05-25 15:42 UTC, Zacharis278 commented on edx_proctoring/api.py
> +            'external_id': attempt['external_id'],
what are we using the external_id/attempt_code for?

2021-05-25 17:07 UTC, idegtiarov commented on edx_proctoring/api.py
> +            'external_id': attempt['external_id'],
It seems that we start hardcode proctortrack provider

@ViktorRusakov  Please pay attention that download_url should be taken from the mock rock directly via the corresponding method which is currently used in the Django template context https://github.com/edx/edx-proctoring/blob/master/edx_proctoring/api.py#L2282

2021-05-25 18:19 UTC, idegtiarov requested changes

2021-05-25 18:19 UTC, idegtiarov commented on edx_proctoring/views.py
> +            review_policy = None
Please add logging of an error msg that is come with the `ProctoredExamReviewPolicyNotFoundException` exception.

2021-05-26 06:11 UTC, ViktorRusakov commented on edx_proctoring/api.py
> +            'external_id': attempt['external_id'],
Yes I missed that, sorry

external_id was used to generate the download url on the frontend since right now our API returns only the base url of the download_url ('http://host.docker.internal:11136'), but the full url contains external_id and exam_id, I didn't realize there was another method for this, I'll fix it now

attempt_code is used for default instructions if backend didn't send any, you can see [here](https://github.com/edx/edx-proctoring/blob/master/edx_proctoring/templates/proctored_exam/instructions.html#L50)
it says exam_code there but it is actually attempt_code as can be seen [here](https://github.com/edx/edx-proctoring/blob/master/edx_proctoring/api.py#L2277)

2021-05-27 13:31 UTC, idegtiarov requested changes
One minor nit, plus extended function and new view requiring tests to be provided.

2021-05-27 13:31 UTC, idegtiarov commented on edx_proctoring/api.py
> +        if attempt['status'] in (ProctoredExamStudentAttemptStatus.created,
Please use rules for splitting long string from the OeX style guideline: https://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python-guidelines.html#breaking-long-lines

2021-05-28 07:55 UTC, idegtiarov approved these changes
Thanks, LGTM, we will improve some minor styling nits in the PR to edx repo though.

2021-05-28 07:55 UTC, merged