[BD-26][EDUCATOR-5808] Add additional data to mfe API responses
raccoongang/edx-proctoring pull request #30
Opened 2021-06-01 11:49 UTC by ViktorRusakov

Updated proctoring setting API to return additional proctoring service data and also updated exam API to return type of the exam

[YouTrack](https://youtrack.raccoongang.com/issue/OeX_Proctoring-198)
[JIRA](https://openedx.atlassian.net/browse/EDUCATOR-5808)

2021-06-02 09:44 UTC, idegtiarov requested changes
one nit please take a look, feel free to ignore

2021-06-02 09:44 UTC, idegtiarov commented on edx_proctoring/utils.py
> +        exam_type = 'proctored'
Nit: I would use following statement as a default so `else` could be omitted, and rewrite variable definitions as a tuple here and in other parts:
```
exam_type, humanized_type = 'proctored', _('a proctored exam')
```
which will make code become a little bit more laconic.

2021-06-02 13:28 UTC, ViktorRusakov commented on edx_proctoring/utils.py
> +        exam_type = 'proctored'
It does look better, thanks, updated!

2021-06-02 15:49 UTC, idegtiarov commented on edx_proctoring/utils.py
> +    return exam_type, humanized_type
I didn't mean exactly that, sorry for misleading.
I'm not a fan of using object by the index it is not clear enough for the review which parameter we are interested in, but we could use named tuples instead. What is your thought on that?

My initial proposal was:
```
    if is_timed_exam:
        exam_type, humanized_type = 'timed', _('a timed exam')
    elif is_practice_exam:        
        if provider and provider.supports_onboarding:
            exam_type, humanized_type = 'onboarding', _('an onboarding exam')
        else:
            exam_type, humanized_type = 'practice', _('a practice exam')

2021-06-02 16:05 UTC, ViktorRusakov commented on edx_proctoring/utils.py
> +    return exam_type, humanized_type
Yeah, my bad... At first I actually thought it is strange that you would like to access the tuple by index when we use result of this function, but then I thought maybe it is better, I should have asked you about it first. I will refactor this

2021-06-03 08:14 UTC, idegtiarov approved these changes
Thanks, let's have it landed

2021-06-03 08:14 UTC, merged