feat: [EXAM-1234] fix autosave of student answers for speaking problems
raccoongang/edx-proctoring pull request #46
Opened 2021-09-17 10:38 UTC by YuriiBorovenskyi

**Description:**
* adds modal windows with notification about answer recording stop before ending/declining student exam;
* updates version of `edx-proctoring` plugin to 2.5.7.

**YouTrack:** https://youtrack.raccoongang.com/issue/EXAM-1234

**Related MR:** 
* [exam/xblock-speaking](https://gitlab.raccoongang.com/hippoteam/exam/edx-ora2/-/merge_requests/**)

**Merge checklist:**

* [ ] All reviewers approved
* [ ] CI build is green
* [x] Demo status: OK
* [ ] All related documentation is updated
* [ ] DevOps notes added

**Post-Merge:**
* [ ] Create `ukr-sertification-juniper-v.2.5.7` tag matching the new version number. (Will be made after merge)

2021-09-17 12:40 UTC, NikolayBorovenskiy requested changes

2021-09-17 12:40 UTC, NikolayBorovenskiy commented on edx_proctoring/static/proctoring/js/views/proctored_exam_view.js
> +                            $stopRecord = $('.stop-record'),
`$stopRecordBtn`?

2021-09-17 12:40 UTC, NikolayBorovenskiy commented on edx_proctoring/static/proctoring/js/views/proctored_exam_view.js
> +                            $stopRecord = $('.stop-record'),
$stopRecordBtn?

2021-09-22 08:24 UTC, YuriiBorovenskyi commented on edx_proctoring/static/proctoring/js/views/proctored_exam_view.js
> +                            $stopRecord = $('.stop-record'),
Fixed to $nextQuestionBtn and $stopRecordingBtn.

2021-09-22 12:40 UTC, NikolayBorovenskiy approved these changes

2021-09-22 12:42 UTC, merged