feat: [EXAM-1357] fixes exam attempt status in completed state after timed exam end
raccoongang/edx-proctoring pull request #50
Opened 2021-11-22 10:51 UTC by YuriiBorovenskyi

**Description:**
* changes attempt status from 'ready to decline' to 'declined' when time is over;
* fixes exam attempt status in completed state after timed exam end;
* updates uk translations;
* updates version of `edx-proctoring` plugin to 2.5.9.

**YouTrack:** https://youtrack.raccoongang.com/issue/EXAM-1357

**Related MR:** 
* [exam/edx-platform]()

**Merge checklist:**

* [ ] All reviewers approved
* [ ] CI build is green
* [ ] Demo status: OK
* [ ] All related documentation is updated
* [ ] DevOps notes added

**Post-Merge:**
* [ ] Create `ukr-sertification-juniper-v.2.5.9` tag matching the new version number. (Will be made after merge)

2021-11-23 10:49 UTC, NikolayBorovenskiy requested changes

2021-11-23 10:49 UTC, NikolayBorovenskiy commented on edx_proctoring/api.py
> +            if attempt.get('status') == 'ready_to_decline':
Please `ProctoredExamStudentAttemptStatus.use ready_to_decline` instead of the plain string.

2021-11-23 10:49 UTC, NikolayBorovenskiy commented on edx_proctoring/api.py
> +            countdown=timedelta(minutes=exam_attempt_obj.allowed_time_limit_mins + 30).total_seconds(),
Please make a constant variable with a good name to put the 30 there and explain there the sense of 30 delta.

2021-11-23 10:49 UTC, NikolayBorovenskiy commented on edx_proctoring/tasks.py
> +}
I suggest expanding the ProctoredExamStudentAttemptStatus. Just move the map logic there and put it into a class method if it is possible. What do you think?

2021-11-23 10:49 UTC, NikolayBorovenskiy commented on edx_proctoring/tasks.py
> +def fix_exam_attempt_status_in_completed_state(self, attempt_id):
`fix_` is bad start for a task name. Please improve the name. Thank you in advance.

2021-11-23 10:49 UTC, NikolayBorovenskiy commented on edx_proctoring/tasks.py
> +    Fix status of exam attempt in completed state.
Also the same point about `Fix status`

2021-11-23 10:49 UTC, NikolayBorovenskiy commented on edx_proctoring/tasks.py
> +        "The task 'fix_exam_attempt_status_in_completed_state' for exam attempt [%d] started successfully.",
`The task 'fix_exam_attempt_status_in_completed_state'` It's bad to write so explicitly in the log string. Please think and improve.

Also `successfully` is extra information here. Please be clear and keep focus.

2021-11-23 10:49 UTC, NikolayBorovenskiy commented on edx_proctoring/tasks.py
> +        "The task 'fix_exam_attempt_status_in_completed_state' for exam attempt [%d] finished successfully.",
`The task 'fix_exam_attempt_status_in_completed_state'` I've already mentioned it.

2021-11-23 11:25 UTC, YuriiBorovenskyi commented on edx_proctoring/api.py
> +            if attempt.get('status') == 'ready_to_decline':
Of course.

2021-11-23 12:22 UTC, YuriiBorovenskyi commented on edx_proctoring/api.py
> +            countdown=timedelta(minutes=exam_attempt_obj.allowed_time_limit_mins + 30).total_seconds(),
Fixed.

2021-11-23 13:56 UTC, YuriiBorovenskyi commented on edx_proctoring/tasks.py
> +}
Agree and fixed.

2021-11-23 14:07 UTC, YuriiBorovenskyi commented on edx_proctoring/tasks.py
> +def fix_exam_attempt_status_in_completed_state(self, attempt_id):
Fixed to `complete_exam_if_attempt_fails` name.

2021-11-23 14:09 UTC, YuriiBorovenskyi commented on edx_proctoring/tasks.py
> +    Fix status of exam attempt in completed state.
Fixed.

2021-11-23 14:48 UTC, YuriiBorovenskyi commented on edx_proctoring/tasks.py
> +        "The task 'fix_exam_attempt_status_in_completed_state' for exam attempt [%d] finished successfully.",
Fixed.

2021-11-23 14:48 UTC, YuriiBorovenskyi commented on edx_proctoring/tasks.py
> +        "The task 'fix_exam_attempt_status_in_completed_state' for exam attempt [%d] started successfully.",
Fixed.

2021-11-25 08:02 UTC, NikolayBorovenskiy approved these changes

2021-11-25 08:07 UTC, merged