feat: [EXAM-1377] adds hardware checker templates for microphone and …
raccoongang/edx-proctoring pull request #53
Opened 2021-12-22 11:32 UTC by Golub-Sergey

**Description:**adds hardware checker templates for microphone and camera

**Youtrack:** https://youtrack.raccoongang.com/issue/EXAM-1377

**Reviewers:**
- [ ] @nikolay.borovenskiy

**Merge checklist:**
- [ ] Demo status: OK
- [ ] All related documentation is updated
- [ ] Commits are squashed
- [ ] DevOps notes added

**Post merge:**
- [ ] Delete the working branch (if not needed anymore)

2021-12-24 17:18 UTC, NikolayBorovenskiy requested changes

2021-12-24 17:18 UTC, NikolayBorovenskiy commented on edx_proctoring/api.py
> +CHECK_HARDWARE_TEMPLATE = {
templates_map

2021-12-24 17:18 UTC, NikolayBorovenskiy commented on edx_proctoring/api.py
> +                    user_id, exam['content_id'],
Bad formating.

2021-12-24 17:18 UTC, NikolayBorovenskiy commented on edx_proctoring/api.py
> +                any(enabled_hardwares) and
Do not understand `any` here.

2021-12-24 17:18 UTC, NikolayBorovenskiy commented on edx_proctoring/api.py
> +                ('is_checking_camera_enabled', context.get('is_checking_camera_enabled')),
U use a lot of plain stings `is_checking_audio_enabled`, `is_checking_audio_enabled`, `is_checking_audio_enabled` in your feature. It should be stored somewhere in one place. In a class or somewhere else. But you need to try to remove copy-paste and make the code reliable.

2021-12-24 17:18 UTC, NikolayBorovenskiy commented on edx_proctoring/api.py
> +            for hardware_name, value in (
Do you need value here?

2021-12-24 17:18 UTC, NikolayBorovenskiy commented on edx_proctoring/api.py
> +        enabled_hardwares = tuple(
Enabled? Maybe available?

2021-12-24 17:18 UTC, NikolayBorovenskiy commented on edx_proctoring/models.py
> +    """
Add one blank line after

2021-12-24 17:18 UTC, NikolayBorovenskiy commented on edx_proctoring/models.py
> +    user_id = models.PositiveIntegerField()
Not foreign key? Are you sure?

2021-12-24 17:18 UTC, NikolayBorovenskiy commented on edx_proctoring/models.py
> +class CourseBlockHardwareChecker(models.Model):
What does it mean CourseBlock?

2021-12-24 17:18 UTC, NikolayBorovenskiy commented on edx_proctoring/models.py
> +    is_checking_camera_enabled = models.BooleanField(default=False)
Maybe it is better to use `passed` instead of `enabled`?

2021-12-24 17:18 UTC, NikolayBorovenskiy commented on edx_proctoring/models.py
> +    ):
Please typing do not forget.

2021-12-24 17:18 UTC, NikolayBorovenskiy commented on edx_proctoring/models.py
> +        )
What? The model method class, which must return yes or no, creates an instance of this model. This is a huge side effect. You can't do that.

2021-12-24 17:18 UTC, NikolayBorovenskiy commented on edx_proctoring/models.py
> +        return False
`return any(not getattr(hardware, hardware_name) for hardware_name in enabled_hardwares))`
?

2021-12-24 17:18 UTC, NikolayBorovenskiy commented on edx_proctoring/models.py
> +        hardware, __ = cls.objects.get_or_create(
Just `hardware` is a bad name.

2021-12-24 17:18 UTC, NikolayBorovenskiy commented on edx_proctoring/templates/timed_exam/check_camera_hardware.html
> +    var msg = "Ви впевнені, що чули звукозапис?";
Did you have a problem with translation?

2021-12-24 17:18 UTC, NikolayBorovenskiy commented on edx_proctoring/templatetags/template_helpers.py
> +from exam_dashboard.utils import extend_url_with_query_parameters as modify_url_with_query_parameters
The proctoring currently uses the `exam_dashboard` package as a dependency. This is bad. I propose to move the `extend_url_with_query_parameters` function to the common utilities and store it there and import it from there already.

2021-12-24 17:18 UTC, NikolayBorovenskiy commented on edx_proctoring/templatetags/template_helpers.py
> +def extend_url_with_query_parameters(url, hardware_checker, hardware_checked):
Haven't you done a tag like this before?

2021-12-24 17:18 UTC, NikolayBorovenskiy commented on edx_proctoring/templatetags/template_helpers.py
> +def extend_url_with_query_parameters(url, hardware_checker, hardware_checked):
Please add typing. Always add typing 🙂

2021-12-27 12:21 UTC, Golub-Sergey commented on edx_proctoring/templatetags/template_helpers.py
> +def extend_url_with_query_parameters(url, hardware_checker, hardware_checked):
No, we haven't

2022-01-04 10:49 UTC, NikolayBorovenskiy approved these changes

2022-01-10 10:44 UTC, merged