feat: [EXAM-1377] added translations and jQuery.MicrophoneChecker plu…
raccoongang/edx-proctoring pull request #55
Opened 2022-01-19 10:57 UTC by PKulkoRaccoonGang

**Description:** 
- added translations and jQuery.MicrophoneChecker plugin

**Youtrack:** 

https://youtrack.raccoongang.com/issue/EXAM-1377

**Reviewers:**
- [ ] @nikolay.borovenskiy

**Merge checklist:**

- [x]  Demo status: OK
- [ ] Commits are squashed

**Post merge:**
- [ ]  Delete the working branch (if not needed anymore)

2022-01-19 14:32 UTC, ihor-romaniuk commented on edx_proctoring/locale/uk/LC_MESSAGES/django.po
> +#~ msgid "{num_of_hours} hour"
Please remove rows starting from `#~`

2022-01-19 14:33 UTC, ihor-romaniuk commented on edx_proctoring/locale/uk/LC_MESSAGES/djangojs.po
> +#, fuzzy
Please remove all `#, fuzzy` rows and closest string below them

2022-01-19 14:36 UTC, ihor-romaniuk commented on edx_proctoring/locale/uk/LC_MESSAGES/djangojs.po
> +#~ msgid "internally reviewed"
Also, all rows starting from `#~` have to be removed because `#~` means that these translation keys haven't been found.

2022-01-24 12:33 UTC, NikolayBorovenskiy requested changes

2022-01-24 12:33 UTC, NikolayBorovenskiy commented on edx_proctoring/static/proctoring/js/proctored_app.js
> +    // initialize jQuery.microphoneChecker plugin
Do we need this comment?

2022-01-24 12:33 UTC, NikolayBorovenskiy commented on edx_proctoring/templates/timed_exam/check_microphone_hardware.html
> +        <p>{% trans "If you still have hardware problems, you can contact technical support by emailing or by calling." %}</p>
Do we need to specify here the email or the phone number of the technical support?

2022-01-24 13:10 UTC, NikolayBorovenskiy commented on edx_proctoring/static/proctoring/js/proctored_app.js
> +        });
Try to keep block `try` as thin as possible. I see that you need to put only microphoneChecker initialisation. Am I right? If so, only this code has to be wrapped into try/catch construction.

2022-01-24 20:39 UTC, PKulkoRaccoonGang commented on edx_proctoring/locale/uk/LC_MESSAGES/django.po
> +#~ msgid "{num_of_hours} hour"
Done

2022-01-24 20:45 UTC, PKulkoRaccoonGang commented on edx_proctoring/locale/uk/LC_MESSAGES/djangojs.po
> +#, fuzzy
Done

2022-01-24 20:46 UTC, PKulkoRaccoonGang commented on edx_proctoring/locale/uk/LC_MESSAGES/djangojs.po
> +#~ msgid "internally reviewed"
Done

2022-01-24 20:49 UTC, PKulkoRaccoonGang commented on edx_proctoring/static/proctoring/js/proctored_app.js
> +    // initialize jQuery.microphoneChecker plugin
Done

2022-01-24 21:00 UTC, PKulkoRaccoonGang commented on edx_proctoring/static/proctoring/js/proctored_app.js
> +        });
Yes you are right

2022-01-25 12:39 UTC, PKulkoRaccoonGang commented on edx_proctoring/templates/timed_exam/check_microphone_hardware.html
> +        <p>{% trans "If you still have hardware problems, you can contact technical support by emailing or by calling." %}</p>
Done

2022-01-26 14:39 UTC, NikolayBorovenskiy approved these changes

2022-01-26 14:39 UTC, merged