fix: [EXAM-1769] resolves checker templetes rendering issues
raccoongang/edx-proctoring pull request #56
Opened 2022-01-19 14:35 UTC by Golub-Sergey

**Description:** resolves checker templetes rendering issues

**Youtrack:** https://youtrack.raccoongang.com/issue/EXAM-1769

**Reviewers:**
- [ ] @nikolay.borovenskiy

**Merge checklist:**

- [x]  Demo status: OK
- [ ] Commits are squashed

**Post merge:**
- [ ]  Delete the working branch (if not needed anymore)

2022-01-24 09:59 UTC, NikolayBorovenskiy requested changes

2022-01-24 09:59 UTC, NikolayBorovenskiy commented on edx_proctoring/templates/timed_exam/check_camera_hardware.html
> +    let msg = "Ви впевнені, що камера працює?";
Please explain to me. Is it possible to use translation flow instead of plain Ukrainian lang?

2022-01-24 09:59 UTC, NikolayBorovenskiy commented on edx_proctoring/templates/timed_exam/check_headphones_hardware.html
> +    let msg = "Ви впевнені, що чули звукозапис?";
Also the same case about translation.

2022-01-24 09:59 UTC, NikolayBorovenskiy commented on edx_proctoring/templates/timed_exam/check_microphone_hardware.html
> +    let msg = "Ви впевнені, що мікрофон працює?";
Also about translation.

2022-01-24 09:59 UTC, NikolayBorovenskiy commented on edx_proctoring/templates/timed_exam/check_microphone_hardware.html
> +  });
I have already seen this code several times. Can we somehow avoid copy-paste. What do you think?

2022-01-24 22:38 UTC, Golub-Sergey commented on edx_proctoring/templates/timed_exam/check_camera_hardware.html
> +    let msg = "Ви впевнені, що камера працює?";
I think yes, but it needs a lot of time to understand  how to compile js translation by js localisation tools

2022-01-26 12:34 UTC, NikolayBorovenskiy approved these changes

2022-01-26 12:34 UTC, merged