feat: [EXAM-1844] added jQuery logics for camera checker
raccoongang/edx-proctoring pull request #57
Opened 2022-01-24 09:59 UTC by PKulkoRaccoonGang

Description:
- new text translation
- jQuery logics 
- section markup

Youtrack:
https://youtrack.raccoongang.com/issue/EXAM-1844

Reviewers:
 @nikolay.borovenskiy
 @ihor-romaniuk

Merge checklist:
- [x] Demo status: OK
- [ ]  All related documentation is updated
- [ ] Commits are squashed
- [ ]  DevOps notes added

Post merge:
- [x]  Delete the working branch (if not needed anymore)

2022-01-24 10:02 UTC, ihor-romaniuk commented on edx_proctoring/static/proctoring/js/proctored_app.js
> +        let $blockVideo = $('#check-camera-video-block', this.element)[0];
It will be better to change `let` to `const` because you will not change it in the future.

2022-01-24 10:03 UTC, ihor-romaniuk commented on edx_proctoring/templates/timed_exam/check_camera_hardware.html
> +        <video id="check-camera-video-block" width="640px" height="360px" style="object-fit: cover" autoplay playsinline
Please check alignments in this file.

2022-01-24 10:03 UTC, PKulkoRaccoonGang commented on edx_proctoring/static/proctoring/js/proctored_app.js
> +        let $blockVideo = $('#check-camera-video-block', this.element)[0];
Done

2022-01-24 10:05 UTC, PKulkoRaccoonGang commented on edx_proctoring/templates/timed_exam/check_camera_hardware.html
> +        <video id="check-camera-video-block" width="640px" height="360px" style="object-fit: cover" autoplay playsinline
Everything is fine in this code)

2022-01-24 10:06 UTC, ihor-romaniuk commented on edx_proctoring/templates/timed_exam/check_camera_hardware.html
> +        <video id="check-camera-video-block" width="640px" height="360px" style="object-fit: cover" autoplay playsinline
You have to use this attributes without `px` -> `width="640" height="360" `

2022-01-24 10:08 UTC, PKulkoRaccoonGang commented on edx_proctoring/templates/timed_exam/check_camera_hardware.html
> +        <video id="check-camera-video-block" width="640px" height="360px" style="object-fit: cover" autoplay playsinline
Done

2022-01-24 10:08 UTC, ihor-romaniuk commented on edx_proctoring/templates/timed_exam/check_camera_hardware.html
> +      if (confirm("Ви впевнені, що камера працює?")) return;
This text should be in English and translated like others.

2022-01-24 10:10 UTC, ihor-romaniuk commented on edx_proctoring/templates/timed_exam/check_camera_hardware.html
> +  $('.btn-success-checking-hardware').click(() => {
What does your event have to do, just show confirm message for the user?

2022-01-24 10:21 UTC, PKulkoRaccoonGang commented on edx_proctoring/templates/timed_exam/check_camera_hardware.html
> +      if (confirm("Ви впевнені, що камера працює?")) return;
Done

2022-01-24 10:23 UTC, PKulkoRaccoonGang commented on edx_proctoring/templates/timed_exam/check_camera_hardware.html
> +  $('.btn-success-checking-hardware').click(() => {
Yes

2022-01-24 11:02 UTC, ihor-romaniuk approved these changes

2022-01-24 12:22 UTC, NikolayBorovenskiy requested changes

2022-01-24 12:22 UTC, NikolayBorovenskiy commented on edx_proctoring/locale/uk/LC_MESSAGES/django.po
> +#| "        "
Why do we need this?

2022-01-24 12:22 UTC, NikolayBorovenskiy commented on edx_proctoring/locale/uk/LC_MESSAGES/django.po
> +#| "            check the system sound settings.\n"
Why do we need this?

2022-01-24 12:22 UTC, NikolayBorovenskiy commented on edx_proctoring/locale/uk/LC_MESSAGES/django.po
> +#| "          "
And this.

2022-01-24 12:22 UTC, NikolayBorovenskiy commented on edx_proctoring/locale/uk/LC_MESSAGES/django.po
> +msgstr ""
No translation here?

2022-01-24 12:22 UTC, NikolayBorovenskiy commented on edx_proctoring/locale/uk/LC_MESSAGES/django.po
> +msgstr ""
No translation here?

2022-01-24 12:22 UTC, NikolayBorovenskiy commented on edx_proctoring/locale/uk/LC_MESSAGES/django.po
> +"Щоб скласти його, потрібно виконати завдання впродовж установленого часу."
Щоб скласти цей екзамен

2022-01-24 12:27 UTC, NikolayBorovenskiy commented on edx_proctoring/locale/uk/LC_MESSAGES/django.po
> +#~ msgstr "{num_of_hours} година"
Please check #~ symbols in this file.

2022-01-24 20:03 UTC, PKulkoRaccoonGang commented on edx_proctoring/locale/uk/LC_MESSAGES/django.po
> +#| "        "
Done

2022-01-24 20:04 UTC, PKulkoRaccoonGang commented on edx_proctoring/locale/uk/LC_MESSAGES/django.po
> +#| "            check the system sound settings.\n"
Done

2022-01-24 20:05 UTC, PKulkoRaccoonGang commented on edx_proctoring/locale/uk/LC_MESSAGES/django.po
> +#| "          "
Done

2022-01-24 20:10 UTC, PKulkoRaccoonGang commented on edx_proctoring/locale/uk/LC_MESSAGES/django.po
> +msgstr ""
We do not need this text, delete

2022-01-24 20:10 UTC, PKulkoRaccoonGang commented on edx_proctoring/locale/uk/LC_MESSAGES/django.po
> +msgstr ""
We do not need this text, delete

2022-01-24 20:11 UTC, PKulkoRaccoonGang commented on edx_proctoring/locale/uk/LC_MESSAGES/django.po
> +"Щоб скласти його, потрібно виконати завдання впродовж установленого часу."
Відредагував на "Щоб скласти цей іспит", done

2022-01-24 20:17 UTC, PKulkoRaccoonGang commented on edx_proctoring/locale/uk/LC_MESSAGES/django.po
> +#~ msgstr "{num_of_hours} година"
I deleted these translations, their originals are in another file

2022-01-25 09:09 UTC, NikolayBorovenskiy approved these changes

2022-01-25 09:17 UTC, merged