feat: [EXAM-2555] add api to check that all exams are completed
raccoongang/edx-proctoring pull request #70
Opened 2024-05-25 17:29 UTC by YuriiBorovenskyi

**Description:**
* add api to check that all exams are completed

**[YouTrack:** https://youtrack.raccoongang.com/issue/EXAM-2555](https://youtrack.raccoongang.com/issue/EXAM-2555)

**Merge checklist:**
* [ ] Demo status: OK

**Post-Merge:**
* [ ] Create `ukr-sertification-juniper-v.2.10.3` tag matching the new version number. (Will be made after merge)

2024-05-26 16:28 UTC, NikolayBorovenskiy requested changes

2024-05-26 16:28 UTC, NikolayBorovenskiy commented on edx_proctoring/api.py
> +    completed_exams_count = ProctoredExamStudentAttempt.objects.get_completed_student_attempts(
`completed_exams`

2024-05-26 16:28 UTC, NikolayBorovenskiy commented on edx_proctoring/api.py
> +    return completed_exams_count == all_exams.count()
`completed_exams.count() == all_exams.count()`

2024-05-27 08:07 UTC, YuriiBorovenskyi commented on edx_proctoring/api.py
> +    completed_exams_count = ProctoredExamStudentAttempt.objects.get_completed_student_attempts(
Fixed.

2024-05-27 08:07 UTC, YuriiBorovenskyi commented on edx_proctoring/api.py
> +    return completed_exams_count == all_exams.count()
Fixed.

2024-05-27 10:04 UTC, NikolayBorovenskiy approved these changes

2024-05-27 10:04 UTC, merged